### ISSUE TITLE
PseCo_FRCNN: 'Shared2FCBBoxHead' object has no attribute 'use_sigmoid'

### ISSUE THREAD

**Issue by ljq2000** [ligang-cs/PseCo#4]

**Comment by ljq2000** [comment]
Traceback (most recent call last):
  File "/root/anaconda3/envs/pseco/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/root/PseCo/ssod/models/PseCo_frcnn.py", line 59, in __init__
    if self.student.roi_head.bbox_head.use_sigmoid:
  File "/root/anaconda3/envs/pseco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Shared2FCBBoxHead' object has no attribute 'use_sigmoid'Traceback (most recent call last):

**Comment by ligang-cs** [comment]
Which version of mmdetection do you use? The attribute "use sigmoid" is suppressed in latest mmdetection, which may account for this error. A suitable mmdetection is already placed in [PseCo/thirdparty/mmdetection](https://github.com/ligang-cs/PseCo/tree/master/thirdparty/mmdetection). Please use it as the default mmdetection for right reproduction.
